# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jS1cq2V1bndHXHtlifwqIyVZrgG-PPtb
"""

def tashxis(belgi):
  if belgi== "istima":
    return "Parasetamol iching"
  elif belgi== "katarakta":
    return "Deksametazon"
  elif belgi== "bosh o'rig'i":
    return "Trimol"
  elif belgi== "gripp":
    return "Taylolhot"
  else:
    return "Shifokorga murojat qiling"
belgi= input("kasallik belgisini kiriting ")
natija=tashxis(belgi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2
def Kubik_rubik(modeli):
  if modeli== "3x3":
    rasm=cv2.imread("3x3.jpg")
    cv2_imshow(rasm)
    return "narxi: 40.000"
  elif modeli== "4x4":
    rasm=cv2.imread("4x4.webp")
    cv2_imshow(rasm)
    return "narxi: 60.000"
  elif modeli== "5x5":
    rasm=cv2.imread("5x5.webp")
    cv2_imshow(rasm)
    return "narxi: 90.000"
  elif modeli== "skewb":
    rasm=cv2.imread("skewb.jpg")
    cv2_imshow(rasm)
    return "narxi: 180.000"
  elif modeli== "pyramid":
    rasm=cv2.imread("pyramid.webp")
    cv2_imshow(rasm)
    return "narxi: 45.000"
  elif modeli== "megaminx":
    rasm=cv2.imread("megaminx.jpg")
    cv2_imshow(rasm)
    return "narxi: 60.000 "
  elif modeli== "orbo ball":
    rasm=cv2.imread("orbo ball.jpg")
    cv2_imshow(rasm)
    return "narxi: 90.000"
  elif modeli== "10x10x10 Sengso Professional":
    rasm=cv2.imread("10x10.jpg")
    cv2_imshow(rasm)
    return "narxi: 2.400.000"
  elif modeli== "Gan 11M Pro":
    rasm=cv2.imread("gan.jpg")
    cv2_imshow(rasm)
    return "narxi: 700.000"
  elif modeli== "mirror":
    rasm=cv2.imread("mirror.webp")
    cv2_imshow(rasm)
    return "narxi: 70.000"
  else:
    return "Batafsil so'rang"
modeli= input("Kubik rubik modeli ")
natija=Kubik_rubik(modeli)
print(natija)